server:
  port: 8082
  error:
    path: /error
    whitelabel:
      enabled: false

spring:
  application:
    name: sharipovrazil-test
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

app:
  name: "To-Do List Manager TEST"
  version: "1.0.0-TEST"
  api:
    version: "2.0.0"
  upload:
    dir: target/test-uploads
  cors:
    allowed-origin: "http://localhost:3000"

logging:
  level:
    com.mipt.sharipovrazil: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.multipart: DEBUG
    org.springframework.test: DEBUG

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false