server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:todo_db}
    username: ${DB_USERNAME:todo_user}
    password: ${DB_PASSWORD:todo_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

logging:
  level:
    com.mipt.sharipovrazil: DEBUG
    org.springframework.web: DEBUG
    org.springframework.beans: DEBUG

app:
  name: "To-Do List Manager DEV"
  version: "1.0.0-DEV"